name: Terraform 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs: 
  Terraform:
    name: Format + Validate + Plan 
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo 
        uses: actions/checkout@v4

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format 
        run: terraform fmt -recursive 

      - name: Terraform init 
        run: terraform init
        working-directory: environments/dev

      - name: Terraform validate 
        run: terraform validate
        working-directory: environments/dev 

      - name: Terraform plan 
        run: terraform plan -input=false
        working-directory: environments/dev