name: Terraform Plan 

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
  create-tfvars:
    name: Generate tfvars
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: environments/dev
    steps: 
      - name: Get repo
        uses: actions/checkout@v4
      - name: Generate tfvars
        run: |
          echo 'environment = "Dev"' > dev.tfvars 
          echo 'project = "CI/CD"' >> dev.tfvars
          echo 'owner = "Bug"' >> dev.tfvars
          echo 'managedby = "Terraform"' >> dev.tfvars
          echo 'ec2_name = "web"' >> dev.tfvars
      - name: Upload tfvars artifact 
        uses: actions/upload-artifact@v4
        with:
          name: tfvars 
          path: environments/dev/dev.tfvars
      - name: Debug + list files 
        run: ls -la 

  terraform-plan:
    name: Format + Init + Validate + Plan 
    runs-on: ubuntu-latest 
    needs: create-tfvars
    defaults: 
      run:
        working-directory: environments/dev 
    steps:
      - name: Get repo 
        uses: actions/checkout@v4
      - name: Download Terraform 
        uses: hashicorp/setup-terraform@v3
      - name: Terraform format 
        run: terraform fmt -check -recursive 
      - name: Terraform init 
        run: terraform init 
      - name: Terraform validate 
        run: terraform validate 
      - name: Download tfvars artifact 
        uses: actions/download-artifact@v4
        with:
          name: tfvars
          path: environments/dev
      - name: Terraform plan 
        run: terraform plan -var-file="dev.tfvars" -out=tfplan 
      - name: Upload tfplan artifact 
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: environments/dev/tfplan
      - name: Debug + list files 
        run: ls -la 

  terraform-apply:
    name: Terraform deploy infra 
    runs-on: ubuntu-latest
    needs: [ create-tfvars, terraform-plan ]
    if: github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: environments/dev
    steps:
      - name: Get repo 
        uses: actions/checkout@v4
      - name: download terraform 
        uses: hashicorp/setup-terraform@v3
      - name: Download tfplan artifact 
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: environments/dev/tfplan 
      - name: Debug files 
        run: ls -la
      - name: Terraform apply 
        run: terraform apply tfplan -auto-approve      
  